@url = http://192.168.56.103:8080
@seid = 19a4f06a

###

POST {{url}}/10415/16777251/316
content-type: application/json
accept: application/json

{
    "host": "mme.epc.hogehoge.net",
    "realm": "epc.hogehoge.net",
    "avp": [{
        "code": 1,
        "mandatory":true,
        "type": "string",
        "data": "4400199998888"
    },{
        "code": 1405,
        "vendorID": 10415,
        "mandatory":true,
        "type": "uint32",
        "data": 2
    }]
}
